In [1]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import mne
import scipy.io
import shutil

In [2]:
%%time
path = './eeg/'
corrupted_files = []
for file in sorted(os.listdir(path)):
    if file.endswith('.edf'):
        try:
            data = mne.io.read_raw_edf(path + file, preload = True);
        except:
            corrupted_files.append(file)

Extracting EDF parameters from E:\ML\THESIS\Protonn\eeg\eeg1.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 1790207  =      0.000 ...  6992.996 secs...
Extracting EDF parameters from E:\ML\THESIS\Protonn\eeg\eeg10.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 1389311  =      0.000 ...  5426.996 secs...
Extracting EDF parameters from E:\ML\THESIS\Protonn\eeg\eeg12.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 1143807  =      0.000 ...  4467.996 secs...
Extracting EDF parameters from E:\ML\THESIS\Protonn\eeg\eeg14.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 953855  =      0.000 ...  3725.996 secs...
Extracting EDF parameters from E:\ML\THESIS\Protonn\eeg\eeg16.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 

EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 1004287  =      0.000 ...  3922.996 secs...
Extracting EDF parameters from E:\ML\THESIS\Protonn\eeg\eeg6.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 1203967  =      0.000 ...  4702.996 secs...
Extracting EDF parameters from E:\ML\THESIS\Protonn\eeg\eeg60.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 967423  =      0.000 ...  3778.996 secs...
Extracting EDF parameters from E:\ML\THESIS\Protonn\eeg\eeg61.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 1492223  =      0.000 ...  5828.996 secs...
Extracting EDF parameters from E:\ML\THESIS\Protonn\eeg\eeg62.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 1498111  =      0.000 ...  5851.996 secs...
Extracting EDF parame

In [13]:
len(data)

908800

In [4]:
corrupted_files

[]

In [5]:
mat = scipy.io.loadmat('eeg/annotations_2017.mat')

In [10]:
len(mat['annotat_new'][0][18][0])

9006

In [19]:
import mne
file = "eeg/eeg1.edf"
data = mne.io.read_raw_edf(file)
raw_data = data.get_data()
# you can get the metadata included in the file and a list of all channels:
info = data.info
channels = data.ch_names

Extracting EDF parameters from E:\ML\THESIS\Protonn\eeg\eeg1.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...


In [23]:
len(file[3:5])

2

In [16]:
for file in sorted(os.listdir(path)):
    print(file)
    print(len(file))
    
    if file.endswith('.edf') and file not in corrupted_files:
        print('second loop file len',len(file))
        if len(file) == 8:
            i = int(file[3]) - 1
            print(i)
        else:
            i = int(file[3:5]) - 1
            print(i)

.ipynb_checkpoints
18
Untitled.ipynb
14
annotations_2017.mat
20
annotations_2017_A_fixed (1).csv
32
annotations_2017_A_fixed.csv
28
annotations_2017_B.csv
22
annotations_2017_C.csv
22
clinical_information.csv
24
eeg1.edf
8
second loop file len 8
0
eeg10.edf
9
second loop file len 9
9
eeg12.edf
9
second loop file len 9
11
eeg14.edf
9
second loop file len 9
13
eeg16.edf
9
second loop file len 9
15
eeg17.edf
9
second loop file len 9
16
eeg18.edf
9
second loop file len 9
17
eeg2.edf
8
second loop file len 8
1
eeg26.edf
9
second loop file len 9
25
eeg30.edf
9
second loop file len 9
29
eeg32.edf
9
second loop file len 9
31
eeg33.edf
9
second loop file len 9
32
eeg34.edf
9
second loop file len 9
33
eeg35.edf
9
second loop file len 9
34
eeg36.edf
9
second loop file len 9
35
eeg37.edf
9
second loop file len 9
36
eeg38.edf
9
second loop file len 9
37
eeg39.edf
9
second loop file len 9
38
eeg4.edf
8
second loop file len 8
3
eeg40.edf
9
second loop file len 9
39
eeg41.edf
9
second loop file len 9


In [23]:
annotations_a = mat['annotat_new'][0][10][0]

In [24]:
len(annotations_a)

7488

In [25]:
d=mat['annotat_new']
d

array([[array([[0, 0, 0, ..., 0, 0, 0],
               [0, 0, 0, ..., 1, 0, 0],
               [0, 0, 0, ..., 0, 0, 0]], dtype=uint8),
        array([[0, 0, 0, ..., 0, 0, 0],
               [0, 0, 0, ..., 0, 0, 0],
               [0, 0, 0, ..., 0, 0, 0]], dtype=uint8),
        array([[0, 0, 0, ..., 0, 0, 0],
               [0, 0, 0, ..., 0, 0, 0],
               [0, 0, 0, ..., 0, 0, 0]], dtype=uint8),
        array([[0, 0, 0, ..., 0, 0, 0],
               [1, 1, 1, ..., 0, 0, 0],
               [0, 0, 0, ..., 0, 0, 0]], dtype=uint8),
        array([[1, 1, 1, ..., 0, 0, 0],
               [1, 1, 1, ..., 1, 0, 0],
               [1, 1, 1, ..., 1, 1, 1]], dtype=uint8),
        array([[0, 0, 0, ..., 0, 0, 0],
               [0, 0, 0, ..., 0, 0, 0],
               [0, 0, 0, ..., 0, 0, 0]], dtype=uint8),
        array([[1, 1, 1, ..., 0, 0, 0],
               [1, 1, 1, ..., 0, 0, 0],
               [1, 1, 1, ..., 0, 0, 0]], dtype=uint8),
        array([[0, 0, 0, ..., 0, 0, 0],
               

In [18]:
file

'reading_eeg.m'

In [5]:
%%time

# Loop through non corrupted edf files

for file in sorted(os.listdir(path)):
    if file.endswith('.edf') and file not in corrupted_files:
        if len(file) == 8:
            i = int(file[3]) - 1
        else:
            i = int(file[3:5]) - 1
    
        # Read eeg values 
        data = mne.io.read_raw_edf(path + file, preload = True)

        # Reading annotations from mat file (expert A only)
        annotations_a = mat['annotat_new'][0][i][0]

        df = pd.DataFrame([x for x in data.get_data()]).T
        df['annotation'] = np.repeat(annotations_a, 256)

        df.to_csv('eldfs/eeg' + str(i) + '.csv', index = False)


Extracting EDF parameters from E:\ML\THESIS\Protonn\eeg\eeg1.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 1790207  =      0.000 ...  6992.996 secs...
Extracting EDF parameters from E:\ML\THESIS\Protonn\eeg\eeg10.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 1389311  =      0.000 ...  5426.996 secs...
Extracting EDF parameters from E:\ML\THESIS\Protonn\eeg\eeg12.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 1143807  =      0.000 ...  4467.996 secs...
Extracting EDF parameters from E:\ML\THESIS\Protonn\eeg\eeg14.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 953855  =      0.000 ...  3725.996 secs...
Extracting EDF parameters from E:\ML\THESIS\Protonn\eeg\eeg16.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 

EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 1004287  =      0.000 ...  3922.996 secs...
Extracting EDF parameters from E:\ML\THESIS\Protonn\eeg\eeg6.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 1203967  =      0.000 ...  4702.996 secs...
Extracting EDF parameters from E:\ML\THESIS\Protonn\eeg\eeg60.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 967423  =      0.000 ...  3778.996 secs...
Extracting EDF parameters from E:\ML\THESIS\Protonn\eeg\eeg61.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 1492223  =      0.000 ...  5828.996 secs...
Extracting EDF parameters from E:\ML\THESIS\Protonn\eeg\eeg62.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 1498111  =      0.000 ...  5851.996 secs...
Extracting EDF parame

# problem

In [8]:
src = './eldf/'
des = './eldfs/'

for file in os.listdir(src):
    if len(file)<9:
        shutil.move(src+file, des+str(int(file[3])+1)+'.csv')
        
    else:
        shutil.move(src+file, des+str(int(float(file[3:5]))+1)+'.csv')
        